# Generated by Django 3.0.7 on 2020-07-08 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_calculator', '0002_auto_20200706_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='wacc',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 33, 55, 221936)),
        ),
    ]
