# Generated by Django 3.0.7 on 2020-07-09 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_calculator', '0004_auto_20200708_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='enterprise_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='description',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='fair_equity_value',
            field=models.FloatField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise',
            name='stock_ticker',
            field=models.CharField(default='all', max_length=200),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='terminal_value',
            field=models.FloatField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise',
            name='todays_value',
            field=models.FloatField(default=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 13, 59, 12, 636550)),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='sector',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='wacc',
            field=models.FloatField(default=0.085),
        ),
    ]
