# Generated by Django 3.0.7 on 2020-07-13 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_calculator', '0007_auto_20200713_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='terminal_value',
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 12, 49, 10, 958200)),
        ),
    ]
