# Generated by Django 3.0.7 on 2020-07-13 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_calculator', '0008_auto_20200713_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 13, 0, 51, 30126)),
        ),
    ]
