# Generated by Django 3.0.7 on 2020-07-14 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_calculator', '0009_auto_20200713_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='terminal_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 10, 56, 58, 931540)),
        ),
    ]
