# Generated by Django 3.0.7 on 2020-07-21 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_calculator', '0011_auto_20200715_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 10, 45, 31, 590588)),
        ),
    ]
