# Generated by Django 3.0.7 on 2020-07-21 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_body', models.CharField(max_length=2000)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 7, 21, 10, 45, 31, 590588))),
            ],
        ),
    ]
