# Generated by Django 3.0.7 on 2020-06-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wacc_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costofequityestimation',
            old_name='market_returns',
            new_name='market_return',
        ),
    ]
